### ISSUE TITLE
Fix issues found with clippy

### ISSUE THREAD

**Issue by rnestler** [spaceapi-community/spaceapi-server-rs#49]
Since #48 we run [clippy](https://github.com/Manishearth/rust-clippy) on every commit. This showed some issues as we can see in [the output of travis](https://travis-ci.org/coredump-ch/spaceapi-server-rs/jobs/145530673#L472).

Fixing those is rather easy and straightforward if someone is looking for an easy issue to get started.

**Comment by dbrgn** [comment]
I'm mentoring this issue if someone needs help to get started.
